# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_anchorpoints <- function(data, n_pieces) {
    .Call('_LocallyStationaryModels_find_anchorpoints', PACKAGE = 'LocallyStationaryModels', data, n_pieces)
}

variogramlsm <- function(z, data, anchorpoints, epsilon, n_angles, n_intervals, dim, kernel_id, print, n_threads) {
    .Call('_LocallyStationaryModels_variogramlsm', PACKAGE = 'LocallyStationaryModels', z, data, anchorpoints, epsilon, n_angles, n_intervals, dim, kernel_id, print, n_threads)
}

findsolutionslsm <- function(anchorpoints, empiricvariogram, squaredweights, dim, mean_x, mean_y, variogram_id, kernel_id, parameters, lowerbound, upperbound, epsilon, lowerdelta, upperdelta, print, n_threads) {
    .Call('_LocallyStationaryModels_findsolutionslsm', PACKAGE = 'LocallyStationaryModels', anchorpoints, empiricvariogram, squaredweights, dim, mean_x, mean_y, variogram_id, kernel_id, parameters, lowerbound, upperbound, epsilon, lowerdelta, upperdelta, print, n_threads)
}

predikt <- function(z, data, anchorpoints, epsilon, delta, dim, solutions, positions, variogram_id, kernel_id, print, n_threads, predict_y) {
    .Call('_LocallyStationaryModels_predikt', PACKAGE = 'LocallyStationaryModels', z, data, anchorpoints, epsilon, delta, dim, solutions, positions, variogram_id, kernel_id, print, n_threads, predict_y)
}

smoothing <- function(solutions, anchorpoints, delta, positions, kernel_id, n_threads) {
    .Call('_LocallyStationaryModels_smoothing', PACKAGE = 'LocallyStationaryModels', solutions, anchorpoints, delta, positions, kernel_id, n_threads)
}

samplelsm <- function(d, variogram_id, parameters, dim, n_samples) {
    .Call('_LocallyStationaryModels_samplelsm', PACKAGE = 'LocallyStationaryModels', d, variogram_id, parameters, dim, n_samples)
}

